apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapi
  labels:
    app: backendapi
spec:
  selector:
    matchLabels:
      app: backendapi
  template:
    metadata:
      labels:
        app: backendapi
    spec:
      containers:
      - name: backendapi
        image: backendapi-image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backendapi
spec:
  selector:
    app: backendapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
