apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageapi
  labels:
    app: imageapi
spec:
  selector:
    matchLabels:
      app: imageapi
  template:
    metadata:
      labels:
        app: imageapi
    spec:
      containers:
      - name: imageapi
        image: imageapi-image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: imageapi
spec:
  selector:
    app: imageapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
